services:
  fertilizer_app:
    env_file: ../system.env
    container_name: fertilizer-app
    image: ${IMAGE_NAME}:${IMAGE_TAG}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    build:
      shm_size: '11gb'
      dockerfile: ./.Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - D:\data\trading\portfolio:/var/local/portfolio
      - D:\data\trading\ray_results:/root/ray_results
      - D:\data\trading\ray_checkpoints:/root/ray_checkpoints
      - D:\data\trading\ray_tmp:/tmp/ray
volumes:
  ray_results: